Remove insecure SpringBoard alerts
calabash/DeviceAgent.iOS pull request #363
Opened 2019-10-25 10:58 UTC by MaksimZhukov

In scope of this PR we have removed the following SpringBoard alerts from all supported languages:
```
  {
    "title": "Some of your %@ data will be sent to Apple to process your requests.",
    "buttons": [
      "OK"
    ],
    "shouldAccept": true
  },

  {
    "title": "Speech data from this app will be sent to Apple to process your requests. This will also help Apple improve its speech recognition technology.",
    "buttons": [
      "OK"
    ],
    "shouldAccept": true
  },
```

2019-10-25 11:05 UTC, maxim-lobanov approved these changes

2019-10-25 11:14 UTC, AndreyMaslennikov approved these changes

2019-10-25 11:25 UTC, maxim-lobanov requested changes
We need to remove those alerts from `tools/springboard-alerts/framework.json` too.

2019-10-25 12:00 UTC, maxim-lobanov approved these changes

2019-10-28 09:33 UTC, jmoody reviewed
What is causing these failing tests:

```
		-[SpringBoardAlertsCurrentLanguageTests testCurrentLanguagezh_Hant_HK]
		-[SpringBoardAlertsCurrentLanguageTests testCurrentLanguagezh_HK]
```

2019-10-28 12:51 UTC, ivan-nosar approved these changes

2019-10-28 12:52 UTC, AndreyMaslennikov approved these changes

2019-10-29 08:35 UTC, merged