[Support] add predicate_string
calabash/DeviceAgent.iOS pull request #374
Opened 2020-02-17 20:14 UTC by agileseph

This PR dedicated to adding predicate_string Query specifier. So it allows using matchingPredicate in a natural way as XCTest provides it with XCUIElementQuery class. The predicate will be evaluated against objects of type id<XCUIElementAttributes>. The basic negative use cases include:
1. If an attribute used incorrectly in predicate string, the app is crashed. So validator should be added a bit later.
2. if the syntax is incorrect for elementType attribute, the user receives expected error with example.
3. if an element type specified incorrect, the user receives expected error about incorrect type.

2020-02-17 20:14 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/calabash/DeviceAgent.iOS?pullRequest=374) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/calabash/DeviceAgent.iOS?pullRequest=374) before we can accept your contribution.<br/><br/>:x: agileseph [sign now](https://cla.opensource.microsoft.com/calabash/DeviceAgent.iOS?pullRequest=374)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/calabash/DeviceAgent.iOS?pullRequest=374) it.</sub>

2020-03-10 07:07 UTC, jmoody requested changes
I am interested in this pull request.

I would be more interested if you updated the run-loop client in parallel and added an integration test that demonstrates that it is working - even against a simulator.

2020-03-10 07:07 UTC, jmoody commented on Server/AutomationActions/Query/Specifiers/QuerySpecifierByPredicate.m
> +    NSString *replacementString = [NSString stringWithFormat:@"elementType == %i", (unsigned int)type];
Always use auto-boxing to print numbers.

```suggestion
    NSString *replacementString = [NSString stringWithFormat:@"elementType == %@", @(type)];
```

This avoids casting and it future proofs against changes in type (recall the transition from 32 bit int to 64 bit int).

2020-03-17 15:18 UTC, agileseph commented
@jmoody I am glad you like this PR. This one is very useful in some tricky cases. Will update code (including RunLoop) regarding your comments and style guide soon. Also, I am happy to add unit/integration tests. Thank you for feedback.

2024-07-22 08:20 UTC, closed without merging