Support iOS 14 Xcode 12
calabash/DeviceAgent.iOS pull request #394
Opened 2020-10-07 17:32 UTC by IlyaBausovAkvelon

This PR uses changes from @JoeSSS branch. See PR: #393 

Changes:
1. Fixed build target architectures issues.
2. Updated private headers.
3. Fixed tests issues.
4. Added support for new alert about local network connections.
5. Fixed issue with locales.

2020-10-07 17:39 UTC, AndreyMaslennikov approved these changes

2020-10-07 17:42 UTC, JoeSSS approved these changes
Nice 👍

2020-10-09 14:32 UTC, ivan-nosar requested changes

2020-10-09 14:32 UTC, ivan-nosar commented on Server/Resources.xcassets/springboard-alerts/springboard-alerts-fr_CA.dataset/alerts.json
> +    "shouldAccept": true
Could you please remove this duplicate

2020-10-09 15:38 UTC, AndreyMaslennikov commented on Server/Resources.xcassets/springboard-alerts/springboard-alerts-fr_CA.dataset/alerts.json
> +    "shouldAccept": true
Removed

2020-10-13 20:42 UTC, ivan-nosar approved these changes

2020-10-29 11:42 UTC, merged