Updated springboard alerts from Xcode 12
calabash/DeviceAgent.iOS pull request #405
Opened 2020-12-14 16:59 UTC by IlyaBausovAkvelon

2020-12-14 17:10 UTC, JoeSSS approved these changes

2020-12-14 17:33 UTC, AndreyMaslennikov commented on Server/Resources.xcassets/springboard-alerts/springboard-alerts-el.dataset/alerts.json
> +      "ΟΚ"
Do we really need to keep duplicated buttons?

2020-12-14 17:33 UTC, AndreyMaslennikov commented on Server/Resources.xcassets/springboard-alerts/springboard-alerts-es.dataset/alerts.json
> +    "shouldAccept": true
We should accept this alert, but "Ahora no" translates as "Not now"

2020-12-14 17:33 UTC, AndreyMaslennikov commented on Server/Resources.xcassets/springboard-alerts/springboard-alerts-es.dataset/alerts.json
> +    "shouldAccept": true
The same as above

2020-12-14 17:33 UTC, AndreyMaslennikov commented on Server/Resources.xcassets/springboard-alerts/springboard-alerts-pt_BR.dataset/alerts.json
> +    "title": "“%1$@” Deseja Ter Acesso às Contas do %2$@",
What does `%1$@` and `%2$@` mean?
AFAIK, the app name in the title should be replaced with `%@`. Are these two parameters?

2020-12-14 17:33 UTC, AndreyMaslennikov commented on Server/Resources.xcassets/springboard-alerts/springboard-alerts-ru.dataset/alerts.json
> +      "ОК"
Same as above for duplicated buttons. But it looks like the first "OK" is typed in latin letters, and the second "ОК" - in Cyrillic.🙂
Could you please confirm?

2020-12-14 17:33 UTC, AndreyMaslennikov commented on Server/Resources.xcassets/springboard-alerts/springboard-alerts-el.dataset/alerts.json
> +      "ΟΚ"
Looks like these to "OK" were typed in different letters (Latin and Cyrillic probably)
Could you please confirm?

2020-12-14 17:35 UTC, AndreyMaslennikov requested changes

2020-12-14 17:35 UTC, AndreyMaslennikov commented on Server/Resources.xcassets/springboard-alerts/springboard-alerts-es.dataset/alerts.json
> +    "shouldAccept": true
We should fix this button at least.
For other comments we need just a small confirmation or explanation.

2020-12-24 18:56 UTC, AndreyMaslennikov approved these changes

2020-12-24 18:56 UTC, merged