Xcode 12.5 new notifications scan
calabash/DeviceAgent.iOS pull request #408
Opened 2021-04-26 08:50 UTC by AlexeyBudynkov

1) Fix of two scripts: collect-all-alerts.rb, update-alerts.rb. They did create this error: `glob': Interrupted system call - /some_path/...lproj (Errno::EINTR)

2) Pulled additional alerts for Xcode 12.5

2021-04-26 15:22 UTC, AlexeyBudynkov commented
integration tests pipeline
https://msmobilecenter.visualstudio.com/Mobile-Center/_build/results?buildId=1069978&view=results

2021-04-27 07:15 UTC, igorFedotenkov commented on tools/springboard-alerts/collect-all-alerts.rb
> +  3.times do |counter|
You don't use counter variable inside loop, so it could be removed:
3.times do ... end

2021-04-27 07:19 UTC, igorFedotenkov approved these changes

2021-04-27 10:01 UTC, AndreyMaslennikov requested changes
The original feature requires handling new alert about "access to advertising identifier" or something like this, so in my understanding we need to add handling for this alerts in this PR

2021-04-29 12:33 UTC, AndreyMaslennikov approved these changes

2021-04-29 12:35 UTC, AlexeyBudynkov commented
Added AppTransparency framework new notifications

2021-04-29 12:50 UTC, merged